user_info: # input your user data
  user_name: "user1"
  password: "user1"

data_config:
  serial_port: "/dev/ttyS0" # ttyS0: UART, ttyACM0: USB (default: UART)
  baudrate: 9600 
  timeout: 10 # Timeout (in seconds) waiting for a response from Raspberry Pi
  start_tag: "<DATA>" # DO NOT CHANGE
  end_tag: "</DATA>"   # DO NOT CHANGE
  url: "https://www.os.his.u-fukui.ac.jp/testpage2/post_sensor/upload.php"

image_config:
  url: "https://www.os.his.u-fukui.ac.jp/testpage2/upload/upload.php"
  output_directory: "images" # Directory name where captured images will be saved
  delete_after_upload: False
  # Set to True to delete the image after uploading it.
  # Recommended for long-term operation to prevent storage from filling up.